### ISSUE TITLE
1.0.4 release

### ISSUE THREAD

**Issue by jonashackt** [codecentric/cxf-spring-boot-starter#1]
@rultor release, tag is `1.0.4.RELEASE`

**Comment by jonashackt** [comment]
@rultor release, tag is `1.0.4.RELEASE`

**Comment by jonashackt** [comment]
@rultor release, tag is `1.0.4.RELEASE`

**Comment by jonashackt** [comment]
@rultor release, tag is `1.0.4.RELEASE`

**Comment by jonashackt** [comment]
@rultor release, tag is `1.0.4.RELEASE`

**Comment by jonashackt** [comment]
@rultor release, tag is `1.0.4.RELEASE`

**Comment by jonashackt** [comment]
@rultor release, tag is `1.0.4.RELEASE`

**Comment by mkanev** [comment]
Hi @jonashackt.
What you did to make it work with correct secret key?
