### ISSUE TITLE
More than one wsdl?

### ISSUE THREAD

**Issue by syg6** [codecentric/cxf-spring-boot-starter#10]
Would it be possible to use more than one wsdl? I followed your tutorial over at codecentric. I added *2*, not 1 wsdl, changed SimpleBootCxfConfiguration to have 2 Endpoints and Clients, created the 2 Endpoint classes, etc.

The Java classes for both wsdl's are generated properly, but when I run spring-boot:run I get this error:

Could not find service named {http://RegistrationServices}Transactions in wsdl file:/.../RetrieveMessages.wsdl

it's looking for services defined in the 2nd wsdl (transactions.wsdl) in the 1st wsdl (retrieveMessages.wsdl).

Is there any way to get this to work, or do I have to run 2 separate Spring Boot apps, one for each wsdl?

Thanks!

**Comment by marcopaga** [comment]
The project supports a single endpoint. I would suggest to run multiple services in this case.

**Comment by jonashackt** [comment]
Like @marcopaga already mentioned, in our current setup with the [ cxf-spring-boot-starter-maven-plugin](https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin) we only support one WSDL file per service.

Although we could develop a feature to support more than one WSDL, we decided to go with more a thing like a Microservice´s approach which is also backed by Spring Boot´s philosophy. 

So if you need more WSDLs (= more services), why not firering up one Spring Boot instance per service?! To better support this scenario we plan to support a service registry (for having one transparent endpoint for all the services) with Spring Cloud Netflix in the near future.

**Comment by jonashackt** [comment]
I opened up #13 to track the further progress and close this issue now.
