### ISSUE TITLE
Show the base package from the scan

### ISSUE THREAD

**Issue by marcopaga** [codecentric/cxf-spring-boot-starter#16]
We were debugging a problem were the implementation was in another package that wasn't considered by the scanner. I would like to add the base packager of the scanner to the output of the failure analyzer:

> Action:
>
>Build a Class that implements your Service Endpoint Interface (SEI): >'de.codecentric.namespace.weatherservice.WeatherService' and is present in a scanned sub-package of: >'de.codecentric'.

**Comment by jonashackt** [comment]
Really interesting case! Was the endpoint in another package then the pom's groupid? How's that possible? I tried hard but couldn't imagine that case 😉

**Comment by marcopaga** [comment]
You're right Jonas. The Endpoint was in a different package. This should normally not be the case but when moving stuff around we changed the package structure.
I figured it out pretty quickly because I was debugging the class loading with you but if somebody comes across this great feature the person will have a nice error message indicating the problem.
