### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean with Spring Boot 1.5.1

### ISSUE THREAD

**Issue by shahidta** [codecentric/cxf-spring-boot-starter#19]
In Spring boot 1.5.*.RELEASE, ServletRegistrationBean is moved to different package org.springframework.boot.web.servlet and as result java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.ServletRegistrationBean error is thrown. Please release compatible version for Spring boot 1.5.0 and onwards release.

**Comment by jonashackt** [comment]
You´re right - we should support 1.5.x as soon as possible. Stay tuned, we´ll work on it :)

**Comment by jonashackt** [comment]
Hi @shahidta - the last commit should fix your Problem. Very strange error, we believe from a non-working combination of Spring Boot and Cloud (Sleuth) dependencies.

We try to release soon, but we´ll need to run some more checks in our environment.

**Comment by jonashackt** [comment]
@shahidta - Release 1.1.1 is out now - including support for Spring Boot 1.5.x - just give the Maven Central replication a few hours, and you should be ready to go!
