### ISSUE TITLE
Handling of reverse proxies

### ISSUE THREAD

**Issue by marcopaga** [codecentric/cxf-spring-boot-starter#20]
Currently it is not possible to publish the CXF Services behind a reverse proxy and return the correct adresses in the WSDL when querying the live service.

Nginx as a reverse proxy with the following location:

nginx config with this location:

`location /service-location {
        
    rewrite ^/service-location/(.*)$ real-endpoint/$1 break;
      
    proxy_pass  http://some-container:8080;

    proxy_set_header Host $host;
    
    proxy_set_header X-Real-IP $remote_addr;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }`

Our CXF Service is running in the docker container some-container on port 8a080.

When calling **nginx/service-location/Service?wsdl** the wsdl will not reflect the correct location of the client (WSDL contains real-endpoint instead of service-location). This makes the WSDL useless for a web service client generation process.

**Comment by marcopaga** [comment]
I added the simple version via a spring property that allows us to set the endpoint url when deploying the service `soap.service.publishedEndpointUrl`.
I'm trying to build a more dynamic and general solution.

**Comment by marcopaga** [comment]
To address this issue I created the [System Tests Project](https://github.com/marcopaga/cxf-spring-boot-starter-system-tests). My goal is to have a dockerized version of our demo service to test out some ideas on a solid ground.

**Comment by jonashackt** [comment]
I think we should think of a more general solution as you mentioned. But I also think we should focus on Spring Cloud Zuul and Eureka for that and shift away from Nginx - tracked in another issue. I think this solution is ok for now and thanks for the contrib @marcopaga !

**Comment by jonashackt** [comment]
Really nice idea and implementation with the relative paths, @marcopaga ! 👍  Should direct that to `1.1.3.RELEASE`

**Comment by jonashackt** [comment]
Will release now :)
