### ISSUE TITLE
wsimport jvm arguments

### ISSUE THREAD

**Issue by akumar2812** [codecentric/cxf-spring-boot-starter#22]
It looks like you are already passing in wsimpot jvm argument "-Djavax.xml.accessExternalSchema=all". I also want to pass in "-Djavax.xml.accessExternalDTD=all".

Is this possible ?

**Comment by marcopaga** [comment]
Currently we pass the argument in the cxf-spring-boot-starter-maven-plugin. Have a look [there](https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin/blob/master/src/main/java/de/codecentric/cxf/BootCxfMojo.java#L124). Adding a parameter is currently not supported. Would you mind adding an issue at the maven plugin? Do you use this plugin?

**Comment by akumar2812** [comment]
I tried passing the jvm arguments to maven plugin and that did not work either. I am not sure how to go about opening issue with maven plugin But I was wondering if you can simply add "-Djavax.xml.accessExternalDTD=all" to the cxf-spring-boot-starter-maven-plugin [line 124](https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin/blob/master/src/main/java/de/codecentric/cxf/BootCxfMojo.java#L124).

**Comment by marcopaga** [comment]
I think we can add it to the plugin. I don't see a point why it's not a sensible default for a general purpose project.  

Do you have any obligations @jonashackt?


Von: akumar2812 <notifications@github.com>(mailto:notifications@github.com)
Antworten: codecentric/cxf-spring-boot-starter <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 22. Februar 2017 at 17:35:22
An: codecentric/cxf-spring-boot-starter <cxf-spring-boot-starter@noreply.github.com>(mailto:cxf-spring-boot-starter@noreply.github.com)
CC: Marco Paga <login-github@marco-paga.eu>(mailto:login-github@marco-paga.eu), Comment <comment@noreply.github.com>(mailto:comment@noreply.github.com)
Betreff: Re: [codecentric/cxf-spring-boot-starter] wsimport jvm arguments (#22)

**Comment by akumar2812** [comment]
Will it be updated in the next build ?

**Comment by jonashackt** [comment]
@marcopaga I think we could add this parameter - should be easy without any problems.

@akumar2812 It will be part of the next release-build :)

**Comment by marcopaga** [comment]
This fix is added to the maven plugin. Will be available with the next release.
