### ISSUE TITLE
Implement Calltime-Logging with Sleuth-Support

### ISSUE THREAD

**Issue by jonashackt** [codecentric/cxf-spring-boot-starter#25]

**Comment by marcopaga** [comment]
Sleuth injects the tracing information into the [MDC](https://logback.qos.ch/manual/mdc.html). When creating the response it is available via `MDC.get("X-B3-TraceId")`. It is available as a tag in kibana with the default logstash config and the log pattern of the app is transparently extended.
If the implementing app wants to respond with a trace id - Having a prozessID in Bipro for example - this response mapping is part of the implementation. Please correct me if I'm wrong.

**Comment by marcopaga** [comment]
IMHO we need to create a ServletFilter that has maintains a stopwatch around the cxf Servlet call. When the call finishes we can put a tag in the MDC. It was called time-calltime before in the starter.

`@Autowired
 private Tracer tracer;

 final Span currentSpan = tracer.getCurrentSpan();
 MDC.put("time-calltime", Long.toString(currentSpan.getAccumulatedMicros() / 1000));`

**Comment by jonashackt** [comment]
Really cool @marcopaga - didn´t know it, but Sleuth makes it also easier here compared to the situation without Sleuth before. Just do a `currentSpan.getAccumulatedMicros()` and you´re there. 👍
