### ISSUE TITLE
Support both SOAP 1.1 and 1.2 at the same time (handling two wsdl:port)

### ISSUE THREAD

**Issue by dtodt** [codecentric/cxf-spring-boot-starter#34]
Greetings, thanks for the tutorial, is very detailed.
On the tutorial, you removed the additional ports to reduce the complexity.

I'm looking for a way to handle multiple versions of soap (1.1 and 1.2) as ports on the same service.

Something like that:
```
<wsdl:service name="someService">
	<wsdl:port name="SomeServicePort11" binding="ns0:SomeServicePortBinding">
		<soap11:address location="https://localhost:443/someService"/>
	</wsdl:port>
	<wsdl:port name="SomeServicePort12" binding="ns2:SomeServicePortBinding">
		<soap12:address location="https://localhost:443/someService"/>
	</wsdl:port>
</wsdl:service>
```

When I used wsimport on wsdl address, it just created one service interface.
I din't find any like that using jax ws, just using the SpringWS implementation.

Thank's in advance.

**Comment by jonashackt** [comment]
We currently don´t support both SOAP 1.1 and 1.2 at the same time, sorry. But PRs are welcome :)
