### ISSUE TITLE
Upgrade base cxf version from 3.2.1 to latest 3.2.5 to get important fix in cxf and wss4j and also provide support for Spring boot 2 :)

### ISSUE THREAD

**Issue by rzteux** [codecentric/cxf-spring-boot-starter#37]
Hi,

Current CXF version used by your starter is quite old (3.2.1 where latest released version is 3.2.5).

Since 3.2.2, CXF references org.apache.wss4j in version 2.2.1 in which there is support to load security properties file from filepath instead of classpath which is very interesting feature when we deploy cxf application where security properties could be different according to destination infrastructure (DevOps context see related fixed issue in wss4j https://issues.apache.org/jira/browse/WSS-540). 

In such scenario we couldn't embed such file in JAR file that could be resolved through the classPath.

For instance I have explicitly excluded cxf dependencies targeting cxf 3.2.1 from your very useful starter to load 3.2.2 instead.

Regards.

**Comment by jonashackt** [comment]
Thanks for reporting! I

**Comment by rzteux** [comment]
Many Many Thanks for this early answer and the future version 👍

**Comment by jonashackt** [comment]
Spring Boot 2.0 upgrade will be done in #33

**Comment by jonashackt** [comment]
Version 1.1.5.RELEASE is released and should be availabe at latest tomorrow morning hopefully (the process of syncing that in the background of Maven Central does always take it´s time). Our tests were successful, would be great to hear your feedback @rzteux

**Comment by rzteux** [comment]
Thks again 😉. You will have my feedback when I will come back from my beginning holiday time 😃.
see you next 22 July 👍
