### ISSUE TITLE
Client only mode and soap logging properties does not recognoise by spring boot?

### ISSUE THREAD

**Issue by fac30ff** [codecentric/cxf-spring-boot-starter#47]
Hello.
I have project based on application.yml, when I trying to use:
soap:
   messages:
      extract: true

and 
endpoint:
   autoinit: false

spring boot do not understand this properties, how to fix this options? spring boot 2.1.6 version of cxf plugin and dep 2.1.7 and 2.1.6 releses

Also may be some one can take me a link to client only soap service with this plugins and dependencies?

**Comment by jonashackt** [comment]
Currently Heroku deployment doesn't work, see https://github.com/codecentric/cxf-spring-boot-starter/issues/48

**Comment by jonashackt** [comment]
@fac30ff will see, if I can get a sample project for you together - was long on my list, but never had the time :smiley:

**Comment by jonashackt** [comment]
Hey @fac30ff I implemented a fully working example client-only project [cxf-boot-simple-client](https://github.com/codecentric/cxf-spring-boot-starter/tree/master/cxf-spring-boot-starter-samples/cxf-boot-simple-client) - have a look especially on the [application.properties](https://github.com/codecentric/cxf-spring-boot-starter/blob/master/cxf-spring-boot-starter-samples/cxf-boot-simple-client/src/main/resources/application.properties) of this project:

```
# Spring Boot configuration
server.port=8095

# SOAP client configuration (which SOAP server we want to access)
webservice.client.url = https://cxf-boot-simple.herokuapp.com/my-foo-api/Weather

# cxf-spring-boot-starter configuration in client-only mode
soap.messages.logging=true
soap.messages.extract=true
endpoint.autoinit=false
```

As this project calls another also new example project [cxf-boot-simple](https://github.com/codecentric/cxf-spring-boot-starter/tree/master/cxf-spring-boot-starter-samples/cxf-boot-simple) which is deployed on Heroku, this configuration could be seen as a reference for your projects.
