### ISSUE TITLE
Make Calltime-Logging optional 

### ISSUE THREAD

**Issue by jonashackt** [codecentric/cxf-spring-boot-starter#5]
If you start with a fresh new project, it´s irritating that you get Console Outputs like 

2016-09-30 09:16:59.837  INFO 28878 --- [nio-8080-exec-5] d.c.cxf.logging.LogCorrelationFilter     : 009 >>> Calltime: 122

Allthough it´s a feature for Elasticsearch Field extraction, this should be configurable (maybe via the soap.messages.extract property)

**Comment by marcopaga** [comment]
We are switching to sleuth with #12. Is this still needed?

If a user doesn't need this kind of tracing I would recommend excluding the dependency.

**Comment by jonashackt** [comment]
You´re right. Let´s close this issue.
