### ISSUE TITLE
inconsistent results from jaxws version 3.3.3,  earlier versions have the same issue

### ISSUE THREAD

**Issue by ronlevings** [codecentric/cxf-spring-boot-starter#53]
From a soap call hitting our implementation method after going through jaxws, the issue is with our bean that  is using big int. The problem is  when input of + and - values.  We are getting inconsistent results causing issues with our venerability scans since the calculations are performed before our validations on the field values

test data results
9 returns in int value of 9 set -  correct
9+9 returns  consistent result eliminating the +
9-9  returns - consistent result making negative after concatenation 
0+0+0+9     returns 9 as expected
12345-12345+9  -returns 539778429 not sure what is happening here ***** ISSUE
12345-1234-9 returns -1234512349  seems to be consistent with earlier results
289 -289 +9  returns -2892899 again consistent with earlier results

**Comment by jonashackt** [comment]
Hmm, seems like an issue of underlying libraries like JAX-WS or CXF... Any suggestions? Maybe there are already bug reports there? Did you have a look on that?

**Comment by jonashackt** [comment]
We have the newest releases of JAX-WS, the maven plugins etc. on board now with https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin/releases/tag/2.3.0.RELEASE - maybe check it again and come back here, if the problem remains.
