### ISSUE TITLE
Autowired constructor not working

### ISSUE THREAD

**Issue by leneinz** [codecentric/cxf-spring-boot-starter#56]
I can't use a constructor with the @Autowired annotation.

```
@Autowired
public endpointImpl(Service service){...}
```

The parameters are null. 
It is only possible with @Autowired fields.
This solves my problem but our team internal convention says that the use of @Autowired constructors is prefered because it makes unit testing easier. 

Is it possible to use Autowired constructors ? 
Its strange that the @Autowired annotation works on fields but not on the constructor and kinda not the way spring works.

**Comment by bjansen** [comment]
I can open a PR for this, if that's OK with you @jonashackt
