### ISSUE TITLE
Complete Automation of Endpoint Initialization

### ISSUE THREAD

**Issue by jonashackt** [codecentric/cxf-spring-boot-starter#6]
Autodetect everything needed to initialize `javax.xml.ws.Endpoint` completely based upon generated Class files.

Background: The [cxf-spring-boot-starter-maven-plugin](https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin) generates two Class files among others:
One representing your Service Endpoint Interface (SEI) - annotated with `javax.jws.WebService` - and another WebServiceClient class - which implements `javax.xml.ws.Service`. Both are needed to initialize the `javax.xml.ws.Endpoint` for publishing it with Apache CXF. In traditional way with Spring Boot, but without the cxf-spring-boot-starter, this is done like that:

```
@Bean
public WeatherService weatherService() {
    return new WeatherServiceEndpoint();
}

@Bean
public Endpoint endpoint() {
    EndpointImpl endpoint = new EndpointImpl(springBus, weatherService());        
    // CXF JAX-WS implementation relies on the correct ServiceName as QName-Object with
    // the name-Attribute´s text <wsdl:service name="Weather"> and the targetNamespace
    // "http://www.codecentric.de/namespace/weatherservice/"
    // Also the WSDLLocation must be set
    endpoint.setServiceName(weather().getServiceName());
    endpoint.setWsdlLocation(weather().getWSDLDocumentLocation().toString());
    endpoint.publish(PUBLISH_URL_ENDING);
    return endpoint;
}

@Bean
public Weather weather() {
    // Needed for correct ServiceName & WSDLLocation to publish contract first incl. original WSDL
    return new Weather();
}
```

Now the idea is, that this is all boilerplate - if you like to run your SOAP web services in a contract first manner. Because then, everything is quite clear from your starting point - the WSDL and XSD files. There you have already the Name of your Service and all it´s methods. It should be possible to initialize the CXF endpoint from that information. Prerequisites remain the generation of the Java classes via the [cxf-spring-boot-starter-maven-plugin](https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin) and a manual implementation of the Service Endpoint Interface (SEI), because that´s the place where you´re service coding starts - we shouldn´t generate that one for you.

With this feature, you dont´t have to do a lot any more - the hole Endpoint initialization (including the definition of a WebService URL) is done for you.

**Comment by jonashackt** [comment]
Also relating:

8908f4176b8ef8ba3222ac6c92b436262667647b 9a04947228319c9700afb841bd75395df2de0489
97c8cac34a6da9335ec75759189bdd4f15c5c588
21c147f9e39f615f92190bb49d8ceee378034d42
3b3135ed954168f9464f66e95adb4c8bb50e51a5
cfcb60d0fbb6e3228c38c60453690e35632607a3
3efb0c59033d8fd242dc541010e513b5524ddb6e

**Comment by jonashackt** [comment]
Idea: The feature is now implemented in a first version - but the reaction if you don´t have an implementation of your SEI is an Exception. It would be better a Failure Analysis shown as [startup failure](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-spring-application.html#_startup_failure).

**Comment by jonashackt** [comment]
Also handle situations, where not only the SEI is annotated with javax.jws.WebService, but also the SEI implementing Endpoint class.

**Comment by jonashackt** [comment]
The Failure Analyzer for the missing SEI implementation is cool, but we should also analyze, if the SEI itself couldn´t be found - along with the WebServiceClient class. So two more Failure Analyzers should be implemented.

**Comment by jonashackt** [comment]
The starter should also work according to Spring Boot´s "backing out" philosophy: If an Endpoint is present, it should refrain from the autoinitialization of the Endpoint (e.g. via an "if this bean is present" @ConditionalOnBean). Also the Endpoint should be accessible from outside the @Configuration Bean - via a getter (maybe with a Cast to the apache CXF EndpointImpl, to have all configuration options).

**Comment by jonashackt** [comment]
Everything is working fine, but not when starting via java -jar. Then currently you get a 

```
016-11-28 11:47:26.487  INFO 92673 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2016-11-28 11:47:27.429 ERROR 92673 --- [ost-startStop-1] o.s.b.c.embedded.tomcat.TomcatStarter    : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'de.codecentric.cxf.configuration.CxfAutoConfiguration': Invocation of init method failed; nested exception is de.codecentric.cxf.diagnostics.SeiNotFoundException: The Service Endpoint Interface (SEI) could´nt be found - an interface that´s annotated with javax.jws.WebService
2016-11-28 11:47:27.452  WARN 92673 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
2016-11-28 11:47:27.456 ERROR 92673 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The Service Endpoint Interface (SEI) could´nt be found - an interface that´s annotated with javax.jws.WebService

Action:

Use the cxf-spring-boot-starter-maven-plugin (https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin) to generate the needed class files from your WSDL & XSDs
```

**Comment by jonashackt** [comment]
The problem seems to be related to the underlying use of fast-classpath-scanner issue https://github.com/lukehutch/fast-classpath-scanner/issues/46 - allthough the scanning in spring boot jars should have been resolved...

**Comment by jonashackt** [comment]
One more step is achieved - now we get an NoSuchMethodException org.apache.cxf.jaxws.JAXWSMethodDispatcher...

Caused by: java.lang.NoSuchMethodException: de.codecentric.soap.endpoint.WeatherServiceEndpoint.getCityWeatherByZIP(de.codecentric.namespace.weatherservice.general.ForecastRequest)
	at java.lang.Class.getMethod(Class.java:1786)
	at org.apache.cxf.jaxws.JAXWSMethodDispatcher.getImplementationMethod(JAXWSMethodDispatcher.java:89)
	at org.apache.cxf.jaxws.JAXWSMethodDispatcher.bind(JAXWSMethodDispatcher.java:56)

**Comment by marcopaga** [comment]
## The WeatherService seems to be ignored by the Scanner because of the single jar layout of spring boot.

### When running the FastClasspathScanner verbosely with java -jar in the sample project I can see that the Service is ignored.

`2017-01-05T22:55:05.893+0100	FastClasspathScanner	Parsing classfile jar:/Users/marco/Projects/v/spring-samples/cxf-boot-simple/target/cxf-boot-simple-0.0.1-SNAPSHOT.jar!BOOT-INF/classes/de/codecentric/namespace/weatherservice/WeatherService.class (took 0,000046 sec)
2017-01-05T22:55:05.893+0100	FastClasspathScanner	-- Class de.codecentric.namespace.weatherservice.WeatherService is at incorrect relative path BOOT-INF/classes/de/codecentric/namespace/weatherservice/WeatherService.class -- ignoring`

`2017-01-05T22:55:05.869+0100	FastClasspathScanner	Ignoring duplicate path BOOT-INF/classes/de/codecentric/namespace/weatherservice/WeatherService.class in classpath element /Users/marco/Projects/v/spring-samples/cxf-boot-simple/target/cxf-boot-simple-0.0.1-SNAPSHOT.jar -- it is masked by the same relative path occurring in an earlier classpath entry`

### Instead when running the tests of the starter in verbose mode the class file is considered:

`2017-01-05T23:06:58.024+0100	FastClasspathScanner	Parsing classfile /Users/marco/Projects/v/cxf-spring-boot-starter/target/test-classes/de/codecentric/namespace/weatherservice/WeatherService.class (took 0,000105 sec)
2017-01-05T23:06:58.024+0100	FastClasspathScanner	-- Found interface class de.codecentric.namespace.weatherservice.WeatherService
2017-01-05T23:06:58.024+0100	FastClasspathScanner	---- Superinterface: java.lang.Object
2017-01-05T23:06:58.024+0100	FastClasspathScanner	---- Annotations: javax.jws.WebService, javax.xml.bind.annotation.XmlSeeAlso`

**Comment by jonashackt** [comment]
You´re right, with `java -jar` fast-classpath-scanner doesn´t seem to work. And with `mvn spring-boot:run` you get the mentioned problems in CXF.

Let´s switch to the Spring variant, [which is after all capable of scanning for Interfaces with specific Annotations](http://stackoverflow.com/questions/17477255/component-scan-for-custom-annotation-on-interface/41504372#41504372) (which I thought it is not and what was the reason started to go with the fast-classpath-scanner).

**Comment by jonashackt** [comment]
The only thing that´s missing is the right package-basename for Spring to scan for the SEI, SEI-Implementation and WebServiceClient classes.

To get this 100% right, we need to use the same mechanism as the cxf-spring-boot-starter-maven-plugin / jaxws-maven-plugin, which itself uses [WSimportTool](https://github.com/gf-metro/jaxws/blob/master/jaxws-ri/tools/wscompile/src/main/java/com/sun/tools/ws/wscompile/WsimportTool.java) of the [JAXWS-RI implementation](https://github.com/gf-metro/jaxws), to obtain the package-Name from the WSDL file, where the classes are generated to

**Comment by jonashackt** [comment]
Oh the namespace-extraction is only suitable for the SEI and the WebServiceClient class - because their package is derived from the WSDL. The SEI implementing class resides mostly not in the same package! We have to find something here to prevent the complete scan with the Dao-Exception because we are scanning org.springframework.

**Comment by jonashackt** [comment]
Now this feature is completely working. For the time beeing (without releases), you need the current cxf-spring-boot-starter-maven-plugin installed via Maven with the [package extraction features](https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin/issues/6).

But the Automation of Endpoint initialization should also consider situations, where it should´nt try to autoinitialize the Endpoints. E.g. if you have an integration test / JAXWS client scenario, you don´t need it. Therefore it should be possible to deactive it - at least via a property. Further deactivation features are not part of this (already long) issue.

**Comment by jonashackt** [comment]
`mvn spring-boot:run` seems to get into trouble with injection an autowired Bean:

```
2017-01-25 09:07:02.530  INFO [bootstrap,,,] 5844 --- [  restartedMain] d.c.c.a.WebServiceAutoDetector           : Found SEI implementing class: 'de.xxx.yyyy.endpoint.LebenSe
rviceEndpoint'
2017-01-25 09:07:02.540  WARN [bootstrap,,,] 5844 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling
refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'de.codecentric.cxf.configuration.XmlValidationConfiguration': Unsa
tisfied dependency expressed through field 'endpoint'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'endpoint' defined
 in class path resource [de/codecentric/cxf/configuration/CxfAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.B
eanInstantiationException: Failed to instantiate [javax.xml.ws.Endpoint]: Factory method 'endpoint' threw exception; nested exception is org.springframework.beans.factory.Unsatisfi
edDependencyException: Error creating bean with name 'seiImplementation': Unsatisfied dependency expressed through field 'lebenServiceController'; nested exception is org.springfra
mework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'de.vorsorge.bipro.controller.LebenServiceController' available: expected at least 1 bean which quali
fies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2017-01-25 09:07:02.552  INFO [bootstrap,,,] 5844 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2017-01-25 09:07:02.702 ERROR [bootstrap,,,] 5844 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Field lebenServiceController in de.vorsorge.bipro.endpoint.LebenServiceEndpoint required a bean of type 'de.xxx.yyy.controller.LebenServiceController' that could not be foun
d.


Action:

Consider defining a bean of type 'de.vorsorge.bipro.controller.LebenServiceController' in your configuration.
```

 and Method matching inside the CXF core:

```
Caused by: java.lang.NoSuchMethodException: de.codecentric.soap.endpoint.WeatherServiceEndpoint.getCityWeatherByZIP(de.codecentric.namespace.weatherservice.general.ForecastRequest)
	at java.lang.Class.getMethod(Class.java:1786)
	at org.apache.cxf.jaxws.JAXWSMethodDispatcher.getImplementationMethod(JAXWSMethodDispatcher.java:89)
	at org.apache.cxf.jaxws.JAXWSMethodDispatcher.bind(JAXWSMethodDispatcher.java:56)
```

All other situations are working correctly - `java -jar service.jar` , a "Run as" inside the IDE or inside `mvn test` scenarios... Very Strange!

**Comment by marcopaga** [comment]
We were using the Spring Boot Devtools to help us speeding up the development. But it seems to be the case that the [two class loaders](http://docs.spring.io/spring-boot/docs/1.4.2.RELEASE/reference/htmlsingle/#using-boot-devtools) used to start the application get in our way. If both classloaders load the same class independent the classes are not equal and Spring won't use these for autowiring components.

**Comment by jonashackt** [comment]
Ah 1000 thanks to you @marcopaga for reporting and sorting that out! I close it again :)

**Comment by sreenu116** [comment]
hi jonashakt de.codecentric.namespace.weatherservice this package is not available so its't loaded project

**Comment by jonashackt** [comment]
Sorry, I don´t really understand... This package isn´t available after first checkout of this project. But if you run a `mvn generate-sources` and have a WSDL file in place like https://github.com/codecentric/cxf-spring-boot-starter/blob/master/src/test/resources/wsdl/Weather1.0.wsdl, there will be a generated package with that exact name under `de.codecentric.namespace.weatherservice`, which is generated from the `targetNamespace="http://www.codecentric.de/namespace/weatherservice/`.
