### ISSUE TITLE
Upgrade to JUnit 5 jupiter

### ISSUE THREAD

**Issue by jonashackt** [codecentric/cxf-spring-boot-starter#69]
Check, if Spring itself also uses JUnit 5 already - and then switch the starter also.

**Comment by jonashackt** [comment]
@marcopaga sadly I didn't saw your branch with the whole work you already did 😭  with Spring Boot 2.4.x not shipping JUnit 4 anymore https://github.com/codecentric/cxf-spring-boot-starter/pull/90 I needed to have a full migration. What I found really cool is the `system-stubs` library as a modern alternative to `system-rule`. What is the magic behind `AssertJ`? I managed to migrate mostly everything to plain JUnit 5 - only the `containsString` stuff is left `hamcrest` dependent...

**Comment by marcopaga** [comment]
Don't worry Jonas. 🙂 Great you found a modern alternative with `system-stubs`. I switched to AssertJ because of personal preference 😬.

**Comment by jonashackt** [comment]
Ok, so we can close this for now and maybe philosophize later 🍻

**Comment by jonashackt** [comment]
See also https://github.com/codecentric/cxf-spring-boot-starter/commit/57020a243bde68b89828f9af31affcd614469f7c , https://github.com/codecentric/cxf-spring-boot-starter/commit/d4f38753b3e3e5e218e04671080975f2c7ecba37 and https://github.com/codecentric/cxf-spring-boot-starter/commit/3cd78294c25ffea194f6f1af9a38fb86472c9e3b
