### ISSUE TITLE
Better Documentation & support of Client-Mode for JAX-WS-Services that are not hostet, but used (incl. example project)

### ISSUE THREAD

**Issue by jonashackt** [codecentric/cxf-spring-boot-starter#8]
You can use this starter also not only for serving SOAP services but also for consuming them with Apache CXF. But this is not documented yet and there´s no example-project or test for this feature.

**Comment by ePaul** [comment]
I just wanted to open an issue asking how to do this. I guess I'll have to browse the code, then.

**Comment by jonashackt** [comment]
We need an integration test for this - not only a system test. We should consider the use of https://github.com/testcontainers/testcontainers-java to run cxf-boot-simple as app inside a Docker container and then integration test onto it.

**Comment by jonashackt** [comment]
Documented in tests & README. So closing now.

**Comment by jonashackt** [comment]
I'am developing an example client-only project right now, that will hopefully also address #41 and #47 - AND document much much better, how to do it. As a second benefit, this will provide us with a real integration test - since the sample client will use another sample project, which is live-deployed on Heroku.
